image: docker:19.03

services:
  - docker:19.03-dind

variables:
  DEV_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - Build
  - Test
  - Deploy

Build Development Image:
  stage: Build
  script:
    - docker build --pull -t $DEV_IMAGE --target development .
    - mkdir tmp
    - docker save $DEV_IMAGE | gzip > tmp/$DEV_TAG.tar.gz
  artifacts:
    expire_in: 10m
    paths:
      - tmp

Unit Tests:
  stage: Test
  variables:
    GIT_STRATEGY: none
  script:
    - docker load -i tmp/$DEV_TAG.tar.gz
    - docker run --rm -e NODE_ENV=test $DEV_IMAGE yarn test

Deploy:
  stage: Deploy
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp/$DEV_TAG.tar.gz
    - docker pull $RELEASE_IMAGE || true
    - docker build --cache-from $DEV_IMAGE --cache-from $RELEASE_IMAGE -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
