image: docker:19.03

services:
  - docker:19.03-dind

variables:
  # DOCKER_DRIVER: overlay2
  # DOCKER_TLS_CERTDIR: "/certs"
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_SHORT_SHA
  # RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

stages:
  - build
  - test

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build Test Image:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE --target development .
    - docker push $TEST_IMAGE

Unit Tests:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run --rm -e NODE_ENV=test $TEST_IMAGE yarn test
