image: docker:19.03

services:
  - docker:19.03-dind

variables:
  TEST_TAG: test-$CI_COMMIT_SHORT_SHA
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_SHORT_SHA

stages:
  - Build
  - Test

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build Test Image:
  stage: Build
  script:
    - docker build --pull -t $TEST_IMAGE --target development .
    - mkdir images
    - docker save $TEST_IMAGE | gzip > images/$TEST_TAG.tar.gz
  artifacts:
    expire_in: 10m
    paths:
      - images

Unit Tests:
  stage: Test
  variables:
    GIT_STRATEGY: none
  script:
    - docker load -i images/$TEST_TAG.tar.gz
    - docker run --rm -e NODE_ENV=test $TEST_IMAGE yarn test
